const data = {
  product: [
    {
      _id: "1",
      name: "Nike Slim",
      category: "Shirts",
      image: "https://source.unsplash.com/680x830/?science",
      price: "125",
      brand: "Nike",
      ratting: "4",
      countInStock: 5,
      numReviews: "12",
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas",
      category: "Shirts",
      image: "https://source.unsplash.com/680x830/?laptop",
      price: "140",
      countInStock: 10,
      brand: "Adidas",
      ratting: "2",
      numReviews: "10",
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike",
      category: "Shirts",
      image: "https://source.unsplash.com/680x830/?bikes",
      price: "120",
      countInStock: 5,
      brand: "Nike",
      ratting: "4",
      numReviews: "17",
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nikerts",
      category: "Shirts",
      image: "https://source.unsplash.com/680x830/?sports",
      price: "120",
      countInStock: 1,
      brand: "Nike",
      ratting: "4",
      numReviews: "27",
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Slim Shirts",
      category: "Shirts",
      image: "https://source.unsplash.com/680x830/?nature",
      price: "120",
      countInStock: 9,
      brand: "Nike",
      ratting: "2.5",
      numReviews: "15",
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Shirts",
      category: "Shirts",
      image: "https://source.unsplash.com/680x830/?games",
      price: "120",
      countInStock: 20,
      brand: "Nike",
      ratting: "1.5",
      numReviews: "9",
      description: "high quality product",
    },
  ],
};
export default data;
